### ISSUE TITLE
RansomTuga Unable to start on both person Computer and RDP after compilation

### ISSUE THREAD

**Issue by aygunbasak** [Tugamer89/RansomTuga#2]
During compilation using .net (sln) it gives an error on functions.cpp in line 57 requesting that the line needs to return a value 'C4716 Error - Must Return a Value'

I added return (0); and it compiled successfully but did not start the Ransomware on my RDP and PC too. I change it to return false; and also compiled successfully but did not start the ransomware program. All errors says missing dll files when the ransomware is started (Stops at Command line interface with about 4 errors instructing to reinstall some files (Probably Visual studio Program). I looked the errors on starkoverflow and discovered the files are from Visual Studio).

I also did this
If I go in to the DLL projects property pages and change the following configuration for a DEBUG build then the built dll no longer provide the desired functionality. If I change it back and rebuild the DLL, then the DLL does provide the correct functionality:

Property Pages => Configuration Properties => C/C++ => Code Generation => Runtime Library => "Multi-threaded Debug DLL (/MDd)" 

Note: If I change to any other, non of the program will compile. but with the default, it only throws 1 function.cpp error I described above.

![Function Error](https://user-images.githubusercontent.com/118870350/203468542-8ae0243a-0ccc-4c48-8545-a18b9e116ab5.PNG)

![Function Edited](https://user-images.githubusercontent.com/118870350/203468810-fff03f25-baa6-466a-8a9b-f5754cd717c1.PNG)

![All Build Successful](https://user-images.githubusercontent.com/118870350/203469095-a05afaa7-02d5-4769-81e9-69a41aca8944.PNG)

![Unable to Run on RDP and PC](https://user-images.githubusercontent.com/118870350/203469763-88e94efa-2936-4da0-bc6e-d0d7fbfc7cbc.PNG)

All attempt to resolve proves abortive. Please help on what to do. Attached are the errors samples.

**Comment by Tugamer89** [comment]
It is supposed to be compiled in `release` `x64`
If you want to use the debug version of the program change enable it in line 47 of `./commons/common.h`: `#define DEBUG true`

**Comment by aygunbasak** [comment]
> It is supposed to be compiled in `release` `x64` If you want to use the debug version of the program change enable it in line 47 of `./commons/common.h`: `#define DEBUG true`
> 
> Let me know if it works

I Did all these above including DEBUG and still got same errors. I ran RansomTuga.exe on RDP without visual studio. Is their any video tutorial on how to install?

This time too, I ran precompilation python script in Ransomtuga folder before opening sln on visual studio. Please if their is any other comprehensive guide on how to compile, direct me to it.

**Comment by aygunbasak** [comment]
> It is supposed to be compiled in `release` `x64` If you want to use the debug version of the program change enable it in line 47 of `./commons/common.h`: `#define DEBUG true`
> 
> Let me know if it works

I was able to get this working. I changed the runtime Library again after choosing Release, x64. It compiled successfully without any other error. I copied to RDP (Rdp doesn't have visual studio) and it gave same errors I described earlier. I then ran from my pc and it was successful because visual studio was installed in it. It only encrypted contents of same release folder it was built in and nothing else. I was expecting all my pc files to be encrypted but did not get that. It did not also send any file to my email (Maybe I configured the email wrongly because I used forwarder).

I ask again, is there anyway it can be made not to depend on visual studio files? it should be independent maybe. Also, how can I make it encrypt all PC files including files on the desktop and other folders too?

**Comment by Tugamer89** [comment]
The python precompile script should run automatically when you click compile (or press F6) in Visual Studio. If that doesn't work try changing the command in `./RansomTuga/preCompilation.bat` and `./RansomTuga/postCompilation.bat` to the command you use to open python from the command prompt. If that doesn't work either, manually specify the precompile events in Visual Studio ([here](https://learn.microsoft.com/cpp/build/specifying-build-events?view=msvc-170) you can find a guide).

In debug mode it automatically encrypts the files in `./debugFolder/` or in a parameter passed when launching the application (i.e. `./RansomTuga.exe C:/Users/` from cmd) otherwise it encrypts the files in the folder where it was started from.

As for the runtime library, I just committed a new update which should have fixed the problem, now the payload is about 700KB heavier (remember to install cryptopp in static mode).

Thanks a lot for reporting these issues!

Let me know if it works so I can close the issue.

**Comment by Tugamer89** [comment]
if no response in 3 days I'll close the issue but feel free to reopen it if you need!
